services:
  postgres:
    image: postgres
    mem_limit: 512m
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - C:\Users\geral\OneDrive\Escritorio\NOVENO SEMESTRE\ARQUITECTURA DE SOFTWARE\LOGS:/var/lib/postgresql/data
    networks:
      - custom-network
  currency-converter:
    image: divisasdemo:5.0.0
    restart: always
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      URL: ${POSTGRES_URL}
      USER_NAME: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - C:\Users\geral\OneDrive\Escritorio\NOVENO SEMESTRE\ARQUITECTURA DE SOFTWARE\LO:/Users/geral/OneDrive/Escritorio/NOVENO SEMESTRE/ARQUITECTURA DE SOFTWARE/X
    depends_on:
      - postgres
    networks:
      - custom-network
  frontend:
    image: angular-software:4.0.0
    ports:
      - "4200:80"
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16
          gateway: 172.10.0.1

