services:
  postgres:
    image: postgres
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: postgres
    volumes:

  currency-converter:
    image: currencydemo 2.0.0
    restart: always
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      URL:
      USERNAME:
      PASSWORD:
    volumes:

    depends_on:
        - postgres